@echo off
chcp 65001 >nul
echo 🚀 ПОЛНОЕ ИСПРАВЛЕНИЕ ПРОЕКТА
echo ========================================

echo 1. Установка пакетов...
pip install django-cors-headers

echo 2. Очистка старых файлов...
if exist db.sqlite3 del db.sqlite3
if exist inventory\migrations\*.py del inventory\migrations\*.py
echo # Generated by fix > inventory\migrations\__init__.py

echo 3. Создание упрощенной модели...
(
echo from django.db import models
echo from core.models import User
echo from catalog.models import Skin
echo.
echo class UserSkin(models.Model):
echo     user = models.ForeignKey(User, on_delete=models.CASCADE)
echo     skin = models.ForeignKey(Skin, on_delete=models.CASCADE)
echo     quantity = models.IntegerField(default=1)
echo     status = models.CharField(max_length=20, default='available')
echo     acquired_date = models.DateTimeField(auto_now_add=True)
echo.
echo     class Meta:
echo         unique_together = ['user', 'skin']
echo.
echo     def __str__(self):
echo         return f"{self.user.username} - {self.skin.name} (x{self.quantity})"
) > inventory\models.py

echo 4. Создание миграций...
python manage.py makemigrations

echo 5. Применение миграций...
python manage.py migrate

echo 6. Создание тестовых данных...
python -c "
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'skintrade.settings')
import django
django.setup()
from django.contrib.auth import get_user_model
User = get_user_model()
user, _ = User.objects.get_or_create(username='admin', defaults={'email':'admin@test.com', 'is_active':True})
user.set_password('admin123')
user.save()
print('✅ Админ создан: admin / admin123')
"

echo.
echo ✅ ВСЁ ИСПРАВЛЕНО!
echo.
echo 📝 Тестирование:
echo 1. python test_windows.py
echo 2. python test_trading.py
echo.
pause